<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
   <?php 
   $lastCrumb = end($crumbs);
   $lastLabel = $lastCrumb['label'] ?? null;
if ($lastLabel instanceof Magento\Framework\Phrase) {
    $lastLabel = (string)$lastLabel;
}

//echo "<pre>"; print_r(get_class_methods(class_name)$crumbs); die(); ?>

<div class="black-bg">
    <div class="breadcrumbs ">
    <div class="page-tittle">
    <h2><?php  echo $lastLabel;?></h2>
</div>
    <ul class="items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="item <?= $block->escapeHtmlAttr($crumbName) ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                   title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                    <?= $block->escapeHtml($crumbInfo['label']) ?>
                </a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
</div>
<?php endif; ?>
