<!-- Footer -->
     <footer class="footer mt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Menü</h5>
                    <ul>
                        <li><a href="#">Alle Düfte</a></li>
                        <li><a href="#">Damendüfte</a></li>
                        <li><a href="#">Herrendüfte</a></li>
                        <li><a href="#">Unisexdüfte</a></li>
                        <li><a href="#">Nischendüfte</a></li>
                        <li><a href="#">Kontakt</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Hilfe</h5>
                    <ul>
                        <li><a href="#">Impressum</a></li>
                        <li><a href="#">AGB</a></li>
                        <li><a href="#">Datenschutz</a></li>
                        <li><a href="#">Widerrufsbelehrung</a></li>
                        <li><a href="#">Über uns</a></li>
                        <li><a href="#">Studentenrabatt</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Inspiration</h5>
                    <ul>
                        <li><a href="#">Orientalische Düfte</a></li>
                        <li><a href="#">Florale Düfte</a></li>
                        <li><a href="#">Frische Düfte</a></li>
                        <li><a href="#">Holzige Düfte</a></li>
                        <li><a href="#">Fruchtige Düfte</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Kontakt</h5>
                    <p>E-mail: support@kaufgeil.com</p>
                    <p>Ein Projekt von Shaban Aleksandrov</p>
                    <p>Leipziger Platz 15 10117 Berlin</p>
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Sicher Bezahlen</h5>
                    <div class="payment-icons">
                        <img src="<?php echo $block->getViewFileUrl('images/applepay.svg'); ?>" alt="Apple Pay">
                        <img src="<?php echo $block->getViewFileUrl('images/amex.svg'); ?>" alt="Amex">
                        <img src="<?php echo $block->getViewFileUrl('images/googlepay.svg'); ?>" alt="Google Pay">
                        <img src="<?php echo $block->getViewFileUrl('images/visa.svg'); ?>" alt="Visa">
                        <img src="<?php echo $block->getViewFileUrl('images/kauf.svg'); ?>" alt="Mastercard">
                        <img src="<?php echo $block->getViewFileUrl('images/kalarna.svg'); ?>" alt="Klarna">
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Seien Sie Sicher</h5>
                    <div class="security-icons">
                        <img src="<?php echo $block->getViewFileUrl('images/garntee.png'); ?>" alt="Trusted Shops">
                        <img class="Trustpilot" src="<?php echo $block->getViewFileUrl('images/trust.png'); ?>" alt="Trustpilot">
                    </div>
                    <ul>
                        <li><span><i class="fa fa-check" aria-hidden="true"></i></span>Käuferschutz bis 70.000€</li>
                        <li><span><i class="fa fa-check" aria-hidden="true"></i></span>geprüfte Sicherheit</li>
                        <li><span><i class="fa fa-check" aria-hidden="true"></i></span>geprüfter Datenschutz</li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                    <h5>Versandpartner</h5>
                    <div class="shipping-icons">
                      <img src="<?php echo $block->getViewFileUrl('images/dhl.png'); ?>" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12 Kaufgeil">
                    <h5>Kaufgeil Folgen</h5>
                    <ul>
                        <li><a href="#">
                            <span><img src="<?php echo $block->getViewFileUrl('images/insta.png'); ?>" alt=""></span>
                        </a></li>
                        <li><a href="#">
                            <span><img src="<?php echo $block->getViewFileUrl('tiktok.png'); ?>" alt=""></span>
                        </a></li>
                    </ul>
                </div>
            </div>
            <!-- <div class="row mt-4 text-center">
               
            </div> -->
        </div>
    </footer>