  <div class="container">
 <?= $block->getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget')->setSliderId(1)->toHtml();?>
<?php echo $block->getLayout()->createBlock("Devcrew\Brand\Block\BrandTab")->setTemplate("Devcrew_Brand::block/brands.phtml")->toHtml(); ?>

        <div class="row mt-3">
            <div class="col mb-4 mt-2">
                <span class="highlight-title text ">Highlights</span>
            </div>
        </div>
        
         <?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('home_highlights')->toHtml();?> 

        <div class="row">
            <div class="col mb-4 mt-2">
                <span class="highlight-title text ">Produkte im Trend</span>
            </div>
        </div>
          <?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('home_produkte_trend')->toHtml();?> 
    <?php
echo $block->getLayout()
    ->createBlock('Mageplaza\Productslider\Block\Widget\Slider')
    ->setData([
        'title' => 'Best Seller',
        'product_type' => 'new',
    ])
    ->toHtml();
?>
    </div>
<!-- <section class="unsere-sec">
    <div class="container mt-2">
      <div class="row "> -->
        
      <!--   <div class="product-wrapper">
          <div class="product-labels">Sale</div>
          <div class="wishlist-icon">
            <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt="" style="color: black;">
          </div>
          <div class="product-image">
            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover" class="hover-img">
          </div>
          <div class="product-info">
            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
            <p class="stng mb-0 mt-2 ">Bvlgari </p>
            <div class="product-rating mt-2">
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="product-rating-count">(27)</span>
            </div>
            <div class="price mt-2 d-flex gap-4">
              <p class="original-price">84,99€</p>
              <p class="discounted-price">68,96€</p>
              <p class="tax-info mx-2 mt-1">inkl</p>
            </div>
          </div>
        </div> -->
 
        <!-- <div class="product-wrapper">
          <div class="product-labels">Sale</div>
          <div class="wishlist-icon">
          <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt="" style="color: black;">
          </div>
          <div class="product-image">
            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover" class="hover-img">
          </div>
          <div class="product-info">
            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
            <p class="stng mb-0 mt-2 ">Bvlgari </p>
            <div class="product-rating mt-2">
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="product-rating-count">(27)</span>
            </div>
            <div class="price mt-2 d-flex gap-4">
              <p class="original-price">84,99€</p>
              <p class="discounted-price">68,96€</p>
              <p class="tax-info mx-2 mt-1">inkl</p>
            </div>
          </div>
        </div>
  -->
 
        <!-- <div class="product-wrapper">
          <div class="product-labels">Sale</div>
          <div class="wishlist-icon">
            <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt="" style="color: black;">
          </div>
          <div class="product-image">
            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover" class="hover-img">
          </div>
          <div class="product-info">
            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
            <p class="stng mb-0 mt-2 ">Bvlgari </p>
            <div class="product-rating mt-2">
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="product-rating-count">(27)</span>
            </div>
            <div class="price mt-2 d-flex gap-4">
              <p class="original-price">84,99€</p>
              <p class="discounted-price">68,96€</p>
              <p class="tax-info mx-2 mt-1">inkl</p>
            </div>
          </div>
        </div> -->
 
        <!-- <div class="product-wrapper">
          <div class="product-labels">Sale</div>
          <div class="wishlist-icon">
             <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt="" style="color: black;">
          </div>
          <div class="product-image">
            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover" class="hover-img">
          </div>
          <div class="product-info">
            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
            <p class="stng mb-0 mt-2 ">Bvlgari </p>
            <div class="product-rating mt-2">
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="product-rating-count">(27)</span>
            </div>
            <div class="price mt-2 d-flex gap-4">
              <p class="original-price">84,99€</p>
              <p class="discounted-price">68,96€</p>
              <p class="tax-info mx-2 mt-1">inkl</p>
            </div>
          </div>
        </div> -->
 
 
        <!-- <div class="product-wrapper">
          <div class="product-labels">Sale</div>
          <div class="wishlist-icon">
             <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt="" style="color: black;">
          </div>
          <div class="product-image">
            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover" class="hover-img">
          </div>
          <div class="product-info">
            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
            <p class="stng mb-0 mt-2 ">Bvlgari </p>
            <div class="product-rating mt-2">
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
              <span class="product-rating-count">(27)</span>
            </div>
            <div class="price mt-2 d-flex gap-4">
              <p class="original-price">84,99€</p>
              <p class="discounted-price">68,96€</p>
              <p class="tax-info mx-2 mt-1">inkl</p>
            </div>
          </div>
        </div> -->
    <!--   </div>
 
    </div>
  </section> -->
    <section class="unsere-sec highlight-section container mt-5">
        <h2 class="mb-4 yellow-border">Im Fokus</h2>
        <div class="row">
            <div class="col-lg-6">
                <div class="highlight-image">
                    <img src="<?php echo $block->getViewFileUrl('images/TDHEDT.jpg'); ?>" alt="Terre d'Hermes Perfume" class="img-fluid">
                </div>
            </div>
            <div class="col-lg-6">
 
                <div class="row">
                    <div class="product-wrapper">
                        <div class="product-labels">Sale</div>
                        <div class="wishlist-icon">
                            <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt=""
                                style="color: black;">
                        </div>
                        <div class="product-image">
                            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
                            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover"
                                class="hover-img">
                        </div>
                        <div class="product-info">
                            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
                            <p class="stng mb-0 mt-2 ">Bvlgari </p>
                            <div class="product-rating mt-2">
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="product-rating-count">(27)</span>
                            </div>
                            <div class="price mt-2 d-flex gap-4">
                                <p class="original-price">84,99€</p>
                                <p class="discounted-price">68,96€</p>
                                <p class="tax-info mx-2 mt-1">inkl</p>
                            </div>
                        </div>
                    </div>
                    <div class="product-wrapper">
                        <div class="product-labels">Sale</div>
                        <div class="wishlist-icon">
                             <img src="<?php echo $block->getViewFileUrl('images/favorite_24dp_434343_FILL0_wght400_GRAD0_opsz24.svg'); ?>" alt=""
                                style="color: black;">
                        </div>
                        <div class="product-image">
                            <img src="<?php echo $block->getViewFileUrl('images/Dior-Sauvage-100ml2-800x800.webp'); ?>" alt="Dior Sauvage" class="main-img">
                            <img src="<?php echo $block->getViewFileUrl('images/Paco-Rabanne-1-Million2-800x800.webp'); ?>" alt="Dior Sauvage Hover"
                                class="hover-img">
                        </div>
                        <div class="product-info">
                            <h3>Hermès Terre d’Hermès Eau de Toilette</h3>
                            <p class="stng mb-0 mt-2 ">Bvlgari </p>
                            <div class="product-rating mt-2">
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="fa fa-star"></span>
                                <span class="product-rating-count">(27)</span>
                            </div>
                            <div class="price mt-2 d-flex gap-4">
                                <p class="original-price">84,99€</p>
                                <p class="discounted-price">68,96€</p>
                                <p class="tax-info mx-2 mt-1">inkl</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
             <?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('home_after_fokus')->toHtml();?> 

    <section class="newsletter-section mt-5">
        <div class="container">

<?php echo $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml();?>

 


          
        </div>
    </section>

