 <!-- Top bar -->
<!--      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<script>
    require(['jquery'], function($) {
        document.getElementById("menu-toggle").addEventListener("click", function () {
        document.getElementById("offcanvas-menu").classList.toggle("show");
    });

    document.getElementById("close-menu").addEventListener("click", function () {
        document.getElementById("offcanvas-menu").classList.remove("show");
    });
    });
</script>
<script>
    require(['jquery'], function($) {
     $(document).ready(function () {
        $('.fa-user-o').on('click', function () {
            var $headerLinks = $('ul.header.links');
            if ($headerLinks.css('display') === 'none') {
                $headerLinks.css('display', 'block');
            } else {
                $headerLinks.css('display', 'none');
            }
        });
    });

    });
</script>
 <?php echo $block->getLayout()->createBlock(\Magento\Cms\Block\Block::class)->setBlockId('header_top_bar')->toHtml();?> 

<!--     <div class="top-header">
        <div class="container">
            <div class="col-md-12">
                <div class="top-bar">
                    <div class="left-top-bar">
                        <a href="#"> 14 TAGE RÜCKGABERECHT</a>
                        <a href="#">1-3 WERKTAGE LIEFERZEIT</a>
                        <a hrrf="#">KOSTENLOSE LIEFERUNG AB 50€</a>
                    </div>
                    <a href="#">ZERTIFIZIERTER HÄNDLER</a>
                </div>

            </div>
        </div>
    </div> -->
    <!-- Header and Navbar -->
    <nav class="navbar navbar-light bg-light d-lg-none">
        <div class="container">
            <button id="menu-toggle" class="btn btn-light">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <div class="header-icons header-icon-for-mobile">
                    <a href="#" class="text-dark"><i class="fa fa-user-o" aria-hidden="true"></i></a>
                </div>
            </button>
<?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>

            <div class="header-icons">
                <a href="#" class="text-dark mdn"><i class="fa fa-user-o" aria-hidden="true"></i></a>
                <a href="#" class="text-dark"><i class="fa fa-heart-o" aria-hidden="true"></i><span
                        class="badge badge-secondary">0</span></a>
                <a href="#" class="text-dark"><i class="fa fa-shopping-bag" aria-hidden="true"></i> <span
                        class="badge badge-secondary erow">0</span></a>
                <a href="#" class="text-dark mdn"> <span class="badge badge-secondary erow"></span> 0,00€</a>
            </div>
        </div>
    </nav>

    <!-- Sidebar Menu -->
    <div id="offcanvas-menu" class="offcanvas">
        <div class="offcanvas-header">
            <input class="form-control mr-sm-2" type="search" placeholder="Nach Produkten suchen" aria-label="Search">
            <button id="close-menu" class="btn btn-light"><i class="fa fa-times" aria-hidden="true"></i>
                Schließen</button>
        </div>
        <div class="offcanvas-body">
            <ul>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/home-svgrepo-com.svg'); ?>" alt="image"></span>
                        START</a></li>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/cart-shopping-svgrepo-com.svg'); ?>"
                                alt="image"></span></i> ALLE PRODUKTE</a></li>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/perfume.svg'); ?>" alt="image"></span> DÜFTE</a></li>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/logo-apple-ar-svgrepo-com.svg'); ?>"
                                alt="image"></span> MARKEN</a></li>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/makeup.svg'); ?>" alt="image"></span> MAKE-UP</a>
                </li>
                <li><a href="#" class="text-dark"><span><img src="<?php echo $block->getViewFileUrl('images/pen-square-svgrepo-com.svg'); ?>"
                                alt="image"></span>EXTRAS</a></li>
                <li><a href="#" class="text-dark"><i class="fa fa-heart-o" aria-hidden="true"></i>WISHLIST</a></li>
                <li><a href="#" class="text-dark"><i class="fa fa-random" aria-hidden="true"></i> VERGLEICHEN</a></li>
                <li><a href="<?php echo $block->getUrl('customer/account'); ?>" class="text-dark"><i class="fa fa-user-o" aria-hidden="true"></i> LOGIN / REGISTER</a>
                </li>
            </ul>
        </div>
    </div>

    <!-- Navbar for desktop -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light d-none d-lg-block">
        <div class="container">
  <?php echo $this->getChildHtml('topsearch') ?>
          <!--   <form class="form-inline search-bar my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Nach Produkten suchen"
                    aria-label="Search">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fa fa-search"
                        aria-hidden="true"></i></button>
            </form> -->
            <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
            <div class="header-icons">
                  <?php echo $this->getChildHtml('topLinks') ?>
                <a href="javascript:void(0)" class="text-dark"><i class="fa fa-user-o" aria-hidden="true"></i></a>
                <a href="<?php echo $block->getUrl('wishlist'); ?>" class="text-dark"><i class="fa fa-heart-o" aria-hidden="true"></i><span
                        class="badge badge-secondary">0</span></a>
                           <?php echo $this->getChildHtml('minicart') ?>
               <!--  <a href="#" class="text-dark"><i class="fa fa-shopping-bag" aria-hidden="true"></i> <span
                        class="badge badge-secondary erow">0</span></a>
                <a href="#" class="text-dark"> <span class="badge badge-secondary erow"></span> 0,00€</a> -->
            </div>
        </div>
    </nav>
   <!-- header toogle css start here -->
    <?php echo $this->getChildHtml('catalogtopnav') ?>
<style type="text/css">
    .account-link {
  display: inline-block;
 font: normal normal normal 14px/1 FontAwesome;
 font-size: inherit;
 text-rendering: auto;
 -webkit-font-smoothing: antialiased;
}
.account-link:before {
  content: "\f007";
  padding-right: 5px;
}
</style>