     <div class="bg-custom-black">
        <div class="container  d-flex align-items-center justify-content-center" style="height:5vh;">
            <div class="container d-flex gap-4 mt-3 ">
                <p class="custom_text text margin">14 TAGE RÜCKGABERECHT</p>
                <p class="text-white text custom_text text margin2">1-3 WERKTAGE LIEFERZEIT</p>
                <p class="text-white text margin3 custom_text text">KOSTENLOSE LIEFERUNG AB 50€</p>
            </div>
            <div>
                <p class="text-white text mx-4 mt-3 custom_text text">
                    ZERTIFIZIERTER HÄNDLER</p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="d-flex justify-content-between align-items-center" style="height:25vh; background-color:white ">
            <div class="d-flex mx-2">
                <div class="search-container ">
                    <input type="text" placeholder="Nach Produkten suchen" class="search-input"
                        style="width:270px; height: 40px;">
                    <img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt="Search Icon"
                        class="search-icon" style="height:20px; margin-left: -30px;">
                </div>
            </div>
             <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
        
            <div class="d-flex mx-3">
                <div class="mx-2 d-flex gap-2">
                    <div><img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt=""
                            style="height: 30px;">
                    </div>
                    <div class="heart-container" style="position: relative; display: inline-block;">
                        <img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt=""
                            style="height: 30px;">
                        <span class="heart-counter"
                            style="position: absolute; top: -5px; right: -5px; font-size: 12px; color: white; background-color: black; padding: 2px 5px; border-radius: 50%; display: flex; justify-content: center; align-items: center; font-weight: normal; font-family: Arial, sans-serif;">0</span>
                    </div>
                    <div class="shopping-bag-container" style="position: relative; display: inline-block;">
                        <img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt=""
                            style="height: 25px;">
                        <span class="shopping-bag-counter"
                            style="position: absolute; top: -5px; right: -5px; font-size: 12px; color: white; background-color: black; padding: 2px 5px; border-radius: 50%; display: flex; justify-content: center; align-items: center; font-weight: normal; font-family: Arial, sans-serif;">0</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="d-flex gap-4 align-items-center justify-content-center" style="margin-left: 180px;">
                <div class="d-flex gap-2 align-items-center">
                    <img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt="" style="height:18px;">
                    <span class="fs-6 text-bold custom-underline custom-link active font ">Start</span>
                </div>
                <div class="d-flex gap-2 align-items-center" style="margin-left: 20px;">
                    <img src="<?php echo $block->getViewFileUrl('images/search_31dp_000000_FILL0_wght400_GRAD0_opsz24.png'); ?>" alt=""
                        style="height: 18px;">
                    <span class="custom-underline font">Alle Produkte</span>
                </div>
                <div class="d-flex gap-2 align-items-center" style="margin-left: 20px;">
                    <div class="dropdown">
                        <div class="d-flex align-items-center">
                            <?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                height="24" viewBox="0 0 24 24" fill="none">
                                <g clip-path="url(#clip0_633_44800)">
                                    <path
                                        d="M11.7663 19.0324C14.3496 19.0324 16.4438 16.9383 16.4438 14.355C16.4438 11.7717 14.3496 9.67749 11.7663 9.67749C9.18304 9.67749 7.08887 11.7717 7.08887 14.355C7.08887 16.9383 9.18304 19.0324 11.7663 19.0324Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path
                                        d="M13.6375 6.87099C13.6375 6.37477 13.4404 5.89888 13.0895 5.548C12.7386 5.19712 12.2627 5 11.7665 5C11.2703 5 10.7944 5.19712 10.4435 5.548C10.0926 5.89888 9.89551 6.37477 9.89551 6.87099V8.27423H13.6375V6.87099Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path
                                        d="M17.9958 10.7748C18.6884 10.427 18.8739 9.39649 18.4101 8.47307C17.9464 7.54965 17.0091 7.08302 16.3165 7.43081C15.6239 7.7786 15.4384 8.80913 15.9021 9.73255C16.3659 10.656 17.3032 11.1226 17.9958 10.7748Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path d="M13.6367 6.87109C14.4799 6.89615 15.2888 7.21012 15.9281 7.76044"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path d="M11.7666 8.27417V9.67741" stroke="#151319" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M7.30273 15.7583H16.2298" stroke="#151319" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M7.55648 7.33862H4.75" stroke="#151319" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M8.02433 5.93549L6.62109 5" stroke="#151319" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M8.02433 8.74194L6.62109 9.67744" stroke="#151319" stroke-width="1.5"
                                        stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                                <defs>
                                    <clipPath id="clip0_633_44800">
                                        <rect width="16" height="16" fill="white" transform="translate(4 4)"></rect>
                                    </clipPath>
                                </defs>
                            </svg>
                            <span class="custom-underline font">Düfte</span>
                        </div>
                        <div class="dropdown-menu custom-dropdown-menu p-4" aria-labelledby="dropdownMenuButton">
                            <div class="row">
                                <div class="col-2">
                                    <h6 class="font">Duft Richtung</h6>
                                    <ul>
                                        <li class="font-3">Duft Richtung</li>
                                        <li class="font-3">Florale Düfte</li>
                                        <li class="font-3">Frische Düfte</li>
                                        <li class="font-3">Fruchtige Düfte</li>
                                        <li class="font-3">Holzige Düfte</li>
                                        <li class="font-3">Orientalische Düfte</li>
                                    </ul>
                                </div>
                                <div class="col-2">
                                    <h6 class="font">Damendüfte</h6>
                                    <ul>
                                        <li class="font-3">Top 10 Damendüfte</li>
                                        <li class="font-3">Frische Düfte</li>
                                        <li class="font-3">Fruchtige Düfte</li>
                                        <li class="font-3">Florale Düfte</li>
                                        <li class="font-3">Holzige Düfte</li>
                                        <li class="font-3">Orientalische Düfte</li>
                                    </ul>
                                </div>
                                <div class="col-2">
                                    <h6 class="font">Herrendüfte</h6>
                                    <ul>
                                        <li class="font-3">Top 10 Herrendüfte</li>
                                        <li class="font-3">Frische Düfte</li>
                                        <li class="font-3">Fruchtige Düfte</li>
                                        <li class="font-3">Florale Düfte</li>
                                        <li class="font-3">Holzige Düfte</li>
                                        <li class="font-3">Orientalische Düfte</li>
                                    </ul>
                                </div>
                                <div class="col-2">
                                    <h6 class="font">Nischendüfte</h6>
                                    <ul>
                                        <li class="font-3">Nischendüfte</li>
                                        <li class="font-3">Nischendüfte Herren</li>
                                        <li class="font-3">Nischendüfte Damen</li>
                                        <li class="font-3">Unisexdüfte</li>
                                    </ul>
                                </div>
                                <div class="col-2">
                                
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div class="d-flex gap-2 align-items-center" style="margin-left: 20px;">
                    <div class="dropdown">

                        <div class="d-flex align-items-center">

                            <?xml version="1.0" encoding="UTF-8"?>
                            <?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                height="24" viewBox="0 0 24 24" fill="none">
                                <g clip-path="url(#clip0_633_44803)">
                                    <path
                                        d="M17.3167 4.75H6.68333C5.61558 4.75 4.75 5.61558 4.75 6.68333V17.3167C4.75 18.3844 5.61558 19.25 6.68333 19.25H17.3167C18.3844 19.25 19.25 18.3844 19.25 17.3167V6.68333C19.25 5.61558 18.3844 4.75 17.3167 4.75Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path
                                        d="M7.65039 10.55V16.3501C7.65039 16.6064 7.75224 16.8523 7.93352 17.0336C8.11481 17.2149 8.36068 17.3167 8.61706 17.3167C8.87343 17.3167 9.11931 17.2149 9.30059 17.0336C9.48188 16.8523 9.58372 16.6064 9.58372 16.3501V10.55H7.65039Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path
                                        d="M10.4324 7.57848L9.583 10.55H7.64967L6.80029 7.57848C6.7672 7.46045 6.77988 7.33428 6.8358 7.2252C6.89171 7.11611 6.98675 7.03215 7.10189 6.99011C7.58555 6.80235 8.09773 6.6986 8.61633 6.68335C9.13494 6.6986 9.64712 6.80235 10.1308 6.99011C10.2459 7.03215 10.341 7.11611 10.3969 7.2252C10.4528 7.33428 10.4655 7.46045 10.4324 7.57848Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path
                                        d="M12.4834 13.45H16.3501V15.3833C16.3501 15.6397 16.2482 15.8855 16.0669 16.0668C15.8856 16.2481 15.6398 16.35 15.3834 16.35H13.4501C13.1937 16.35 12.9478 16.2481 12.7665 16.0668C12.5852 15.8855 12.4834 15.6397 12.4834 15.3833V13.45Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                    <path d="M16.3501 10.55H12.4834V13.45H16.3501V10.55Z" stroke="#151319"
                                        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path
                                        d="M13.4501 7.6499H15.3834C15.6398 7.6499 15.8856 7.75175 16.0669 7.93303C16.2482 8.11432 16.3501 8.36019 16.3501 8.61657V10.5499H12.4834V8.61657C12.4834 8.36019 12.5852 8.11432 12.7665 7.93303C12.9478 7.75175 13.1937 7.6499 13.4501 7.6499V7.6499Z"
                                        stroke="#151319" stroke-width="1.5" stroke-linecap="round"
                                        stroke-linejoin="round"></path>
                                </g>
                                <defs>
                                    <clipPath id="clip0_633_44803">
                                        <rect width="16" height="16" fill="white" transform="translate(4 4)"></rect>
                                    </clipPath>
                                </defs>
                            </svg>
                            <span class="custom-underline font">Marken</span>
                        </div>


                        <div class="dropdown-menu custom-dropdown-menu-2 p-4" aria-labelledby="dropdownMenuButton">
                            <div class="row">
                                <div class="col-2">
                                    <h6 class="font">Chanel</h6>
                                    <ul>
                                        <li class="font-3">Dior</li>
                                        <li class="font-3">Estée Lauder</li>
                                        <li class="font-3">Jean Paul Gaultier</li>
                                        <li class="font-3">Paco Rabanne</li>
                                        <li class="font-3">Tom Ford</li>
                                        <li class="font-3">Yves Saint Laurent</li>
                                    </ul>
                                    
                                </div>
                                <div class="col-2">
                                    <h6 class="font">Abercrombie & Fitch</h6>
                                    <ul>
                                
                                        <li class="font-3">Burberry</li>
                                        <li class="font-3">Bvlgari</li>
                                        <li class="font-3">Byredo</li>
                                        <li class="font-3">Carolina Herrera</li>
                                        <li class="font-3">Chanel</li>
                                        <li class="font-3">Chloé</li>
                                    </ul>
                                    
                                </div>
                                <div class="col-2">
                                    <ul>
                                        <li class="font-3">Creed</li>
                                        <li class="font-3">Davidoff</li>
                                        <li class="font-3">Dior</li>
                                        <li class="font-3">Dolce&Gabbana</li>
                                        <li class="font-3">Duracell</li>
                                        <li class="font-3">Estée Lauder</li>
                                        <li class="font-3">Gucci</li>
                                    </ul>
                                    
                                </div>
                                <div class="col-2">
                                    <ul>
                                        <li class="font-3">Guerlain</li>
                                        <li class="font-3">Issey Miyake</li>
                                        <li class="font-3">Jean Paul Gaultier</li>
                                        <li class="font-3">Lamy</li>
                                        <li class="font-3">Lancome</li>
                                        <li class="font-3">Maison Margiela</li>
                                        <li class="font-3">Marc Jacobs</li>
                                    </ul>
                                    
                                </div>
                                <div class="col-2">
                                    <ul>
                                        <li class="font-3">Narciso Rodriguez</li>
                                        <li class="font-3">Paco Rabanne</li>
                                        <li class="font-3">Prada</li>
                                        <li class="font-3">Tom Ford</li>
                                        <li class="font-3">Versace</li>
                                        <li class="font-3">Yves Saint Laurent</li>
                                        <li class="font-3">Serge Lutens</li>
                                    </ul>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="d-flex gap-2 align-items-center" style="margin-left: 20px;">
                    <?xml version="1.0" encoding="UTF-8"?> <svg xmlns="http://www.w3.org/2000/svg" width="18px"
                        height="18px" viewBox="0 0 24 24" fill="none">
                        <path
                            d="M11 4H7.2C6.0799 4 5.51984 4 5.09202 4.21799C4.71569 4.40974 4.40973 4.7157 4.21799 5.09202C4 5.51985 4 6.0799 4 7.2V16.8C4 17.9201 4 18.4802 4.21799 18.908C4.40973 19.2843 4.71569 19.5903 5.09202 19.782C5.51984 20 6.0799 20 7.2 20H16.8C17.9201 20 18.4802 20 18.908 19.782C19.2843 19.5903 19.5903 19.2843 19.782 18.908C20 18.4802 20 17.9201 20 16.8V12.5M15.5 5.5L18.3284 8.32843M10.7627 10.2373L17.411 3.58902C18.192 2.80797 19.4584 2.80797 20.2394 3.58902C21.0205 4.37007 21.0205 5.6364 20.2394 6.41745L13.3774 13.2794C12.6158 14.0411 12.235 14.4219 11.8012 14.7247C11.4162 14.9936 11.0009 15.2162 10.564 15.3882C10.0717 15.582 9.54378 15.6885 8.48793 15.9016L8 16L8.04745 15.6678C8.21536 14.4925 8.29932 13.9048 8.49029 13.3561C8.65975 12.8692 8.89125 12.4063 9.17906 11.9786C9.50341 11.4966 9.92319 11.0768 10.7627 10.2373Z"
                            stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                    <span class="custom-underline font">Extras</span>
                </div>
            </div>
        </div>
    </div>





























