<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Customers') ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <?php /* @escapeNotVerified */ //echo __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?>
         <p><?php /* @escapeNotVerified */ echo __('Wenn Sie sich für diese Website registrieren, können Sie auf Ihren Bestellstatus und -verlauf zugreifen. Füllen Sie einfach die nachstehenden Felder aus und wir werden im Handumdrehen ein neues Konto für Sie einrichten. Wir werden Sie nur um Informationen bitten, die notwendig sind, um den Kaufprozess schneller und einfacher zu machen.') ?></p>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action create primary btn btn-default btn-lg"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
